# Generated by Django 3.0.6 on 2020-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lenguaje', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
    ]
