# Generated by Django 3.0.6 on 2020-06-06 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='id',
        ),
        migrations.AddField(
            model_name='api',
            name='categoria',
            field=models.CharField(default='premios', max_length=200),
        ),
        migrations.AddField(
            model_name='api',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=200),
        ),
        migrations.AddField(
            model_name='api',
            name='nombre',
            field=models.CharField(default='evento', max_length=100),
        ),
        migrations.AddField(
            model_name='api',
            name='nombre_artista',
            field=models.CharField(default='Artista_name', max_length=100),
        ),
        migrations.AddField(
            model_name='api',
            name='url_page',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='api',
            name='vivo',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
