# Generated by Django 3.0.6 on 2020-06-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200606_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='lenguaje',
        ),
        migrations.RemoveField(
            model_name='api',
            name='name',
        ),
        migrations.RemoveField(
            model_name='api',
            name='precio',
        ),
    ]
